### ISSUE TITLE
No Admin Rights

### ISSUE THREAD

**Issue by jimbok8** [sblantipodi/JavaFastScreenCapture#5]
This looks really interesting.
Is it possible to make a version of the installer that does not require admin rights please?
Perhaps just something that unpacks the files?
Thanks
Jim

**Comment by sblantipodi** [comment]
Hi @jimbok8 
thanks for the kind post.

Project is growing really really fast, I am going to release a new version in some days with a new user interface.

All the "manual configurations" will be replaced soon with a simple UI, LED matrix will be automatically calculated considering the monitor resolution and operating system scaling.

I am honest, I don't have time to implement this feature in this moment but I will surely implement it in the next releases.
This is an open source project, you can read the source, you can trust it even with admin rights :) but I agree this is a needed feature for a next release.

If you like the project, don't forget to cast a star and to subscribe to be informed on new releases.

Thanks

**Comment by sblantipodi** [comment]
@jimbok8 at the end is was pretty easyer to implement your request, I have just released a new version with per user basis that does not require admin rights.
thanks for the suggestion!
